export const STYLES = [
  "Modern",
  "Minimal",
  "Bold",
  "Elegant",
  "Playful",
  "Corporate",
  "Luxury",
  "Editorial",
  "Neon",
  "Warm",
];

export const CATEGORIES = [
  { id: "food", name: "Restaurant & Cafe", blurb: "Menus, bookings, promos, delivery CTA." },
  { id: "realestate", name: "Real Estate", blurb: "Listings, agents, lead capture, trust." },
  { id: "fitness", name: "Fitness & Wellness", blurb: "Programs, schedules, memberships, results." },
  { id: "beauty", name: "Beauty Salon & Spa", blurb: "Services, pricing, appointments, gallery." },
  { id: "services", name: "Local Services", blurb: "Handyman, cleaning, HVAC, quick quotes." },
  { id: "education", name: "Education & Tutoring", blurb: "Courses, enrollment, credibility, FAQs." },
  { id: "portfolio", name: "Portfolio & Creative", blurb: "Show work, win clients, look premium." },
  { id: "events", name: "Events & Wedding", blurb: "RSVP, schedules, vendors, locations." },
  { id: "shop", name: "Mini Shop", blurb: "Product catalog, bundles, socials, CTA." },
  { id: "tech", name: "Tech & Startup", blurb: "SaaS landing, waitlists, pricing, demos." },
];

const money = (n) => Math.round(n);

const baseIncludes = [
  "Responsive layout (mobile-first)",
  "Modern sections & spacing",
  "SEO-friendly structure",
  "Fast load (no backend)",
  "Easy color + font swap",
];

const pagesCommon = ["Home", "About", "Services", "Contact"];

/**
 * 50 catalogue items (10 categories × 5 products)
 * Note: These are “products” in your catalogue; you can later add real live previews.
 */
export const ITEMS = [
  // Restaurant & Cafe (5)
  {
    sku: "FOOD-001",
    categoryId: "food",
    name: "Bistro Bloom",
    style: ["Warm", "Elegant"],
    price: money(79),
    short: "Cozy cafe vibe with menu highlights and reservation CTA.",
    pitch:
      "Perfect for cafes and bistros that want a premium feel. Hero + signature dishes + simple reservation section so customers take action fast.",
    pages: ["Home", "Menu", "Reservations", "Gallery", "Contact"],
    bestFor: ["Cafes", "Bistros", "Brunch spots"],
    includes: [...baseIncludes, "Menu layout section", "Reservation CTA block"],
    tags: ["cafe", "menu", "reservation", "warm", "elegant"],
    accent: { a: "#f97316", b: "#f43f5e", c: "#facc15" },
    featuredRank: 2,
    addedAt: "2026-01-05",
  },
  {
    sku: "FOOD-002",
    categoryId: "food",
    name: "Sushi Neon",
    style: ["Neon", "Bold"],
    price: money(89),
    short: "High-contrast dark theme with neon accents and promo blocks.",
    pitch:
      "Built for modern restaurants that run weekly promos. Strong visuals, bold typographic hierarchy, and a clean CTA to order/reserve.",
    pages: ["Home", "Menu", "Promos", "Locations", "Contact"],
    bestFor: ["Sushi", "Ramen", "Night eateries"],
    includes: [...baseIncludes, "Promo banner system", "Location cards"],
    tags: ["neon", "restaurant", "promo", "dark", "bold"],
    accent: { a: "#22c55e", b: "#06b6d4", c: "#a855f7" },
    featuredRank: 6,
    addedAt: "2026-01-10",
  },
  {
    sku: "FOOD-003",
    categoryId: "food",
    name: "Pasta Minimal",
    style: ["Minimal", "Editorial"],
    price: money(69),
    short: "Clean editorial layout with menu story and chef section.",
    pitch:
      "A calm, premium minimal template for Italian restaurants. Focuses on story, ingredients, and a menu that’s easy to scan.",
    pages: ["Home", "Menu", "Our Story", "Chef", "Contact"],
    bestFor: ["Italian", "Fine casual", "New openings"],
    includes: [...baseIncludes, "Editorial typography", "Chef profile section"],
    tags: ["minimal", "editorial", "menu", "chef"],
    accent: { a: "#0ea5e9", b: "#1f2937", c: "#f59e0b" },
    featuredRank: 9,
    addedAt: "2025-12-28",
  },
  {
    sku: "FOOD-004",
    categoryId: "food",
    name: "Street Food Pop",
    style: ["Playful", "Bold"],
    price: money(59),
    short: "Energetic layout for food trucks with social proof.",
    pitch:
      "Built for quick decisions: what you sell, where you are today, and how to order. Includes a fun testimonial strip and IG-ready gallery.",
    pages: ["Home", "Today’s Location", "Menu", "Reviews", "Contact"],
    bestFor: ["Food trucks", "Street snacks", "Pop-up stalls"],
    includes: [...baseIncludes, "Daily location section", "Testimonial strip"],
    tags: ["playful", "food-truck", "bold", "social"],
    accent: { a: "#fb7185", b: "#22c55e", c: "#f59e0b" },
    featuredRank: 12,
    addedAt: "2026-01-12",
  },
  {
    sku: "FOOD-005",
    categoryId: "food",
    name: "Bakery Luxe",
    style: ["Luxury", "Elegant"],
    price: money(99),
    short: "Soft luxury look for bakeries and dessert brands.",
    pitch:
      "A premium bakery template: hero, best-sellers, seasonal box, and a strong order CTA. Perfect for brands that sell gift boxes.",
    pages: ["Home", "Best Sellers", "Seasonal", "FAQ", "Contact"],
    bestFor: ["Bakeries", "Desserts", "Gift boxes"],
    includes: [...baseIncludes, "Best-seller cards", "FAQ accordion (static)"],
    tags: ["luxury", "bakery", "elegant", "gift"],
    accent: { a: "#f472b6", b: "#a78bfa", c: "#fde68a" },
    featuredRank: 1,
    addedAt: "2026-01-14",
  },

  // Real Estate (5)
  {
    sku: "RE-001",
    categoryId: "realestate",
    name: "Skyline Realtor",
    style: ["Corporate", "Modern"],
    price: money(109),
    short: "Trust-focused agent site with lead form and listings grid.",
    pitch:
      "Made for realtors: credibility first. Hero + featured listings + reviews + lead form that converts.",
    pages: ["Home", "Listings", "About Agent", "Reviews", "Contact"],
    bestFor: ["Independent agents", "Small agencies", "New agents"],
    includes: [...baseIncludes, "Listings grid layout", "Lead capture section"],
    tags: ["real-estate", "agent", "lead", "corporate"],
    accent: { a: "#2563eb", b: "#06b6d4", c: "#0f172a" },
    featuredRank: 3,
    addedAt: "2026-01-09",
  },
  {
    sku: "RE-002",
    categoryId: "realestate",
    name: "Palm Villa",
    style: ["Luxury", "Warm"],
    price: money(129),
    short: "Luxury property landing with gallery and amenities section.",
    pitch:
      "High-end vibe for premium listings. Focused on images, amenities, and strong CTA to schedule a viewing.",
    pages: ["Home", "Gallery", "Amenities", "Neighborhood", "Contact"],
    bestFor: ["Luxury listings", "Villas", "High-end rentals"],
    includes: [...baseIncludes, "Amenities icons", "Neighborhood highlights"],
    tags: ["luxury", "villa", "gallery", "warm"],
    accent: { a: "#f59e0b", b: "#14b8a6", c: "#0f172a" },
    featuredRank: 5,
    addedAt: "2026-01-03",
  },
  {
    sku: "RE-003",
    categoryId: "realestate",
    name: "Loft Minimal",
    style: ["Minimal", "Editorial"],
    price: money(99),
    short: "Editorial listing template with clean typography.",
    pitch:
      "Minimal and premium—great for modern apartments. Clean grid sections and a straightforward inquiry CTA.",
    pages: ["Home", "Property", "Floor Plan", "FAQ", "Contact"],
    bestFor: ["Apartments", "Lofts", "Modern condos"],
    includes: [...baseIncludes, "Floor plan section", "FAQ accordion (static)"],
    tags: ["minimal", "editorial", "apartment", "listing"],
    accent: { a: "#111827", b: "#06b6d4", c: "#9ca3af" },
    featuredRank: 10,
    addedAt: "2025-12-30",
  },
  {
    sku: "RE-004",
    categoryId: "realestate",
    name: "Suburb Starter",
    style: ["Warm", "Modern"],
    price: money(79),
    short: "Friendly family-home vibe with quick contact options.",
    pitch:
      "For agents selling family homes: clear benefits, trust signals, and simple call-to-action blocks for fast inquiries.",
    pages: ["Home", "Listings", "Buying Tips", "Selling Tips", "Contact"],
    bestFor: ["Family homes", "Local brokers", "First-time buyers"],
    includes: [...baseIncludes, "Tips sections", "Quick contact CTA"],
    tags: ["family", "warm", "realtor", "tips"],
    accent: { a: "#22c55e", b: "#f97316", c: "#0ea5e9" },
    featuredRank: 14,
    addedAt: "2026-01-01",
  },
  {
    sku: "RE-005",
    categoryId: "realestate",
    name: "Investor Deck",
    style: ["Corporate", "Bold"],
    price: money(119),
    short: "Data-forward template for property investors and rentals.",
    pitch:
      "A serious look for investors: metrics blocks, portfolio grid, and a CTA for partnership/inquiries.",
    pages: ["Home", "Portfolio", "Metrics", "Case Studies", "Contact"],
    bestFor: ["Investors", "Rental managers", "Small funds"],
    includes: [...baseIncludes, "Metrics strip", "Case study layout"],
    tags: ["investor", "metrics", "corporate", "bold"],
    accent: { a: "#a855f7", b: "#0ea5e9", c: "#0f172a" },
    featuredRank: 7,
    addedAt: "2026-01-11",
  },

  // Fitness & Wellness (5)
  {
    sku: "FIT-001",
    categoryId: "fitness",
    name: "Lift Lab",
    style: ["Bold", "Modern"],
    price: money(89),
    short: "Gym landing with programs, schedule, and transformation section.",
    pitch:
      "A high-energy gym template focused on programs and results. Includes transformation spotlight and membership CTA.",
    pages: ["Home", "Programs", "Schedule", "Trainers", "Contact"],
    bestFor: ["Gyms", "Strength coaching", "Cross training"],
    includes: [...baseIncludes, "Schedule section", "Results spotlight"],
    tags: ["gym", "bold", "programs", "results"],
    accent: { a: "#ef4444", b: "#f59e0b", c: "#22c55e" },
    featuredRank: 4,
    addedAt: "2026-01-08",
  },
  {
    sku: "FIT-002",
    categoryId: "fitness",
    name: "Yoga Calm",
    style: ["Minimal", "Warm"],
    price: money(69),
    short: "Soft calm layout for yoga studios and instructors.",
    pitch:
      "A peaceful, friendly layout with class schedule, instructor bio, and a simple ‘Book a class’ CTA.",
    pages: ["Home", "Classes", "Instructor", "Pricing", "Contact"],
    bestFor: ["Yoga", "Pilates", "Wellness coaches"],
    includes: [...baseIncludes, "Class cards", "Pricing layout"],
    tags: ["yoga", "calm", "minimal", "wellness"],
    accent: { a: "#14b8a6", b: "#a78bfa", c: "#fde68a" },
    featuredRank: 11,
    addedAt: "2025-12-26",
  },
  {
    sku: "FIT-003",
    categoryId: "fitness",
    name: "Run Club Neon",
    style: ["Neon", "Playful"],
    price: money(59),
    short: "Energetic community vibe for running clubs and events.",
    pitch:
      "Designed for communities: upcoming runs, route info, and a strong join CTA. Great for local clubs.",
    pages: ["Home", "Upcoming Runs", "Routes", "Community", "Contact"],
    bestFor: ["Run clubs", "Community events", "Fitness groups"],
    includes: [...baseIncludes, "Event list section", "Route highlight blocks"],
    tags: ["community", "neon", "events", "playful"],
    accent: { a: "#22c55e", b: "#06b6d4", c: "#f472b6" },
    featuredRank: 15,
    addedAt: "2026-01-13",
  },
  {
    sku: "FIT-004",
    categoryId: "fitness",
    name: "Nutrition Studio",
    style: ["Editorial", "Modern"],
    price: money(79),
    short: "Nutrition coach site with services, packages, and FAQ.",
    pitch:
      "A credibility-first template: clear service packages, testimonial highlights, and an FAQ to reduce buyer questions.",
    pages: ["Home", "Services", "Packages", "Reviews", "Contact"],
    bestFor: ["Nutritionists", "Health coaches", "Online coaching"],
    includes: [...baseIncludes, "Package cards", "FAQ accordion (static)"],
    tags: ["nutrition", "editorial", "packages", "trust"],
    accent: { a: "#0ea5e9", b: "#22c55e", c: "#111827" },
    featuredRank: 13,
    addedAt: "2026-01-06",
  },
  {
    sku: "FIT-005",
    categoryId: "fitness",
    name: "Spa Reset",
    style: ["Luxury", "Elegant"],
    price: money(99),
    short: "Luxury wellness spa feel with services and booking CTA.",
    pitch:
      "A high-end wellness layout with premium spacing and soft gradients. Ideal for spas or wellness retreats.",
    pages: ["Home", "Treatments", "Packages", "Gallery", "Contact"],
    bestFor: ["Spas", "Retreats", "Wellness studios"],
    includes: [...baseIncludes, "Treatment cards", "Package layout"],
    tags: ["luxury", "spa", "elegant", "booking"],
    accent: { a: "#f472b6", b: "#06b6d4", c: "#a78bfa" },
    featuredRank: 8,
    addedAt: "2026-01-02",
  },

  // Beauty Salon & Spa (5)
  {
    sku: "BEAUTY-001",
    categoryId: "beauty",
    name: "Salon Glow",
    style: ["Elegant", "Warm"],
    price: money(79),
    short: "Service menu + stylist profiles + booking CTA.",
    pitch:
      "A friendly premium salon template with a clean services grid, stylist spotlight, and simple appointment CTA.",
    pages: ["Home", "Services", "Stylists", "Gallery", "Contact"],
    bestFor: ["Hair salons", "Barbers", "Nail studios"],
    includes: [...baseIncludes, "Services grid", "Team profiles"],
    tags: ["salon", "beauty", "elegant", "booking"],
    accent: { a: "#fb7185", b: "#a78bfa", c: "#fde68a" },
    featuredRank: 16,
    addedAt: "2026-01-04",
  },
  {
    sku: "BEAUTY-002",
    categoryId: "beauty",
    name: "Barber Bold",
    style: ["Bold", "Modern"],
    price: money(69),
    short: "Strong typography for barbers with pricing and hours.",
    pitch:
      "A clean barber landing with clear pricing cards, opening hours, and a big call-to-action to book.",
    pages: ["Home", "Services", "Pricing", "Reviews", "Contact"],
    bestFor: ["Barbers", "Men’s grooming", "Modern salons"],
    includes: [...baseIncludes, "Pricing cards", "Review strip"],
    tags: ["barber", "bold", "pricing", "modern"],
    accent: { a: "#0ea5e9", b: "#111827", c: "#f59e0b" },
    featuredRank: 18,
    addedAt: "2025-12-29",
  },
  {
    sku: "BEAUTY-003",
    categoryId: "beauty",
    name: "Skincare Minimal",
    style: ["Minimal", "Luxury"],
    price: money(99),
    short: "Premium skincare clinic style with trust sections.",
    pitch:
      "Made for skincare clinics: clean minimal layout, treatment packages, and trust sections (certifications, reviews).",
    pages: ["Home", "Treatments", "Packages", "Before & After", "Contact"],
    bestFor: ["Skincare clinics", "Aesthetics", "Dermal therapy"],
    includes: [...baseIncludes, "Before/after layout", "Certification strip"],
    tags: ["skincare", "minimal", "luxury", "clinic"],
    accent: { a: "#a78bfa", b: "#06b6d4", c: "#f1f5f9" },
    featuredRank: 17,
    addedAt: "2026-01-07",
  },
  {
    sku: "BEAUTY-004",
    categoryId: "beauty",
    name: "Nail Pop",
    style: ["Playful", "Neon"],
    price: money(59),
    short: "Fun color-forward template for nail artists.",
    pitch:
      "A high-energy vibe for nail studios: gallery first, packages, and social proof. Designed to look great on phones.",
    pages: ["Home", "Gallery", "Packages", "Reviews", "Contact"],
    bestFor: ["Nail salons", "Nail artists", "Beauty freelancers"],
    includes: [...baseIncludes, "Gallery grid", "Package cards"],
    tags: ["nails", "playful", "neon", "gallery"],
    accent: { a: "#f472b6", b: "#22c55e", c: "#06b6d4" },
    featuredRank: 19,
    addedAt: "2026-01-12",
  },
  {
    sku: "BEAUTY-005",
    categoryId: "beauty",
    name: "Spa Serenity",
    style: ["Elegant", "Editorial"],
    price: money(89),
    short: "Editorial spa layout with calm sections and packages.",
    pitch:
      "A calm premium spa template: package tiers, treatment list, and subtle luxury feel to justify higher pricing.",
    pages: ["Home", "Treatments", "Packages", "FAQ", "Contact"],
    bestFor: ["Spas", "Massage", "Wellness"],
    includes: [...baseIncludes, "Package tiers", "FAQ accordion (static)"],
    tags: ["spa", "elegant", "editorial", "packages"],
    accent: { a: "#14b8a6", b: "#a78bfa", c: "#fde68a" },
    featuredRank: 20,
    addedAt: "2025-12-27",
  },

  // Local Services (5)
  {
    sku: "SERV-001",
    categoryId: "services",
    name: "Handy Hero",
    style: ["Bold", "Corporate"],
    price: money(79),
    short: "Handyman template with services list and quote CTA.",
    pitch:
      "Built to convert: services, areas served, before/after gallery, and a clear ‘Get a quote’ section.",
    pages: ["Home", ...pagesCommon, "Get a Quote"],
    bestFor: ["Handyman", "Repairs", "Home services"],
    includes: [...baseIncludes, "Quote CTA section", "Areas served list"],
    tags: ["handyman", "quote", "local", "services"],
    accent: { a: "#f59e0b", b: "#0ea5e9", c: "#111827" },
    featuredRank: 21,
    addedAt: "2026-01-06",
  },
  {
    sku: "SERV-002",
    categoryId: "services",
    name: "Clean Sweep",
    style: ["Minimal", "Warm"],
    price: money(69),
    short: "Cleaning service website with packages and reviews.",
    pitch:
      "Great for cleaning businesses: package tiers, reviews, and a strong scheduling CTA.",
    pages: ["Home", "Services", "Packages", "Reviews", "Contact"],
    bestFor: ["Home cleaning", "Office cleaning", "Deep cleaning"],
    includes: [...baseIncludes, "Package tiers", "Review strip"],
    tags: ["cleaning", "packages", "warm", "minimal"],
    accent: { a: "#06b6d4", b: "#22c55e", c: "#0ea5e9" },
    featuredRank: 23,
    addedAt: "2025-12-31",
  },
  {
    sku: "SERV-003",
    categoryId: "services",
    name: "HVAC Pro",
    style: ["Corporate", "Modern"],
    price: money(89),
    short: "HVAC/AC repair template with emergency callouts.",
    pitch:
      "A trustworthy, professional look with emergency callouts, service details, and quick contact blocks.",
    pages: ["Home", "Services", "Emergency", "Reviews", "Contact"],
    bestFor: ["AC repair", "HVAC", "Emergency services"],
    includes: [...baseIncludes, "Emergency banner", "Service cards"],
    tags: ["hvac", "repair", "corporate", "trust"],
    accent: { a: "#2563eb", b: "#22c55e", c: "#0f172a" },
    featuredRank: 22,
    addedAt: "2026-01-02",
  },
  {
    sku: "SERV-004",
    categoryId: "services",
    name: "Painter Pop",
    style: ["Playful", "Modern"],
    price: money(59),
    short: "Color-focused painter template with project gallery.",
    pitch:
      "For painting services: show projects, offer packages, and collect leads with a friendly CTA.",
    pages: ["Home", "Projects", "Services", "Pricing", "Contact"],
    bestFor: ["Painters", "Renovation", "Decor services"],
    includes: [...baseIncludes, "Project gallery layout", "Pricing cards"],
    tags: ["painter", "projects", "playful", "gallery"],
    accent: { a: "#f97316", b: "#a855f7", c: "#06b6d4" },
    featuredRank: 24,
    addedAt: "2026-01-13",
  },
  {
    sku: "SERV-005",
    categoryId: "services",
    name: "Law Office Minimal",
    style: ["Minimal", "Corporate"],
    price: money(119),
    short: "Clean attorney website with practice areas and credibility.",
    pitch:
      "A clean, credible layout with practice areas, trust badges, and an easy consultation CTA.",
    pages: ["Home", "Practice Areas", "Attorney", "FAQ", "Contact"],
    bestFor: ["Lawyers", "Consultants", "Professional services"],
    includes: [...baseIncludes, "Practice areas grid", "Trust badge strip"],
    tags: ["law", "minimal", "corporate", "credibility"],
    accent: { a: "#111827", b: "#2563eb", c: "#f59e0b" },
    featuredRank: 25,
    addedAt: "2026-01-09",
  },

  // Education & Tutoring (5)
  {
    sku: "EDU-001",
    categoryId: "education",
    name: "Tutor Track",
    style: ["Modern", "Warm"],
    price: money(69),
    short: "Tutoring site with subjects, packages, and testimonials.",
    pitch:
      "Built for tutors: show subjects, package tiers, and parent/student testimonials to build trust.",
    pages: ["Home", "Subjects", "Packages", "Results", "Contact"],
    bestFor: ["Tutors", "Coaching", "After-school"],
    includes: [...baseIncludes, "Subject cards", "Package tiers"],
    tags: ["tutoring", "packages", "warm", "trust"],
    accent: { a: "#22c55e", b: "#0ea5e9", c: "#f59e0b" },
    featuredRank: 26,
    addedAt: "2026-01-05",
  },
  {
    sku: "EDU-002",
    categoryId: "education",
    name: "Course Canvas",
    style: ["Editorial", "Modern"],
    price: money(89),
    short: "Course landing with modules, outcomes, and enrollment CTA.",
    pitch:
      "Great for selling a single course. Includes outcomes, module preview, and a CTA designed to convert.",
    pages: ["Home", "Curriculum", "Outcomes", "Pricing", "Contact"],
    bestFor: ["Online courses", "Bootcamps", "Workshops"],
    includes: [...baseIncludes, "Curriculum sections", "Outcome blocks"],
    tags: ["course", "editorial", "curriculum", "enroll"],
    accent: { a: "#a855f7", b: "#06b6d4", c: "#111827" },
    featuredRank: 27,
    addedAt: "2026-01-10",
  },
  {
    sku: "EDU-003",
    categoryId: "education",
    name: "Kids Learn Pop",
    style: ["Playful", "Bold"],
    price: money(59),
    short: "Fun bright layout for kids classes and learning centers.",
    pitch:
      "Playful and colorful with clear sections for age groups, class schedule, and parent FAQs.",
    pages: ["Home", "Programs", "Schedule", "FAQ", "Contact"],
    bestFor: ["Kids classes", "Learning centers", "After-school"],
    includes: [...baseIncludes, "Age group cards", "Schedule section"],
    tags: ["kids", "playful", "bold", "schedule"],
    accent: { a: "#f97316", b: "#22c55e", c: "#06b6d4" },
    featuredRank: 28,
    addedAt: "2026-01-01",
  },
  {
    sku: "EDU-004",
    categoryId: "education",
    name: "Language Studio",
    style: ["Minimal", "Elegant"],
    price: money(79),
    short: "Language school template with levels and enrollment.",
    pitch:
      "A calm, premium look: levels, placement info, and a clear enrollment CTA.",
    pages: ["Home", "Levels", "Teachers", "Pricing", "Contact"],
    bestFor: ["Language schools", "Private tutors", "Small academies"],
    includes: [...baseIncludes, "Level comparison table", "Teacher profiles"],
    tags: ["language", "minimal", "elegant", "enroll"],
    accent: { a: "#0ea5e9", b: "#a78bfa", c: "#111827" },
    featuredRank: 29,
    addedAt: "2025-12-25",
  },
  {
    sku: "EDU-005",
    categoryId: "education",
    name: "STEM Bootcamp",
    style: ["Neon", "Bold"],
    price: money(99),
    short: "High-tech look for STEM programs with countdown CTA.",
    pitch:
      "For bootcamps: modern tech visuals, outcomes, and enrollment CTA. Great for coding and STEM programs.",
    pages: ["Home", "Curriculum", "Outcomes", "Mentors", "Contact"],
    bestFor: ["Bootcamps", "STEM programs", "Coding schools"],
    includes: [...baseIncludes, "Mentor profiles", "Outcome sections"],
    tags: ["stem", "neon", "bold", "bootcamp"],
    accent: { a: "#22c55e", b: "#a855f7", c: "#06b6d4" },
    featuredRank: 30,
    addedAt: "2026-01-14",
  },

  // Portfolio & Creative (5)
  {
    sku: "PORT-001",
    categoryId: "portfolio",
    name: "Studio Noir",
    style: ["Luxury", "Editorial"],
    price: money(99),
    short: "Editorial portfolio with case studies and bold imagery.",
    pitch:
      "Premium studio portfolio: case studies, services, and a CTA that feels high-end.",
    pages: ["Home", "Work", "Case Study", "Services", "Contact"],
    bestFor: ["Designers", "Studios", "Branding"],
    includes: [...baseIncludes, "Case study layout", "Project grid"],
    tags: ["portfolio", "editorial", "luxury", "case-study"],
    accent: { a: "#111827", b: "#a855f7", c: "#06b6d4" },
    featuredRank: 31,
    addedAt: "2026-01-08",
  },
  {
    sku: "PORT-002",
    categoryId: "portfolio",
    name: "Photographer Minimal",
    style: ["Minimal", "Elegant"],
    price: money(79),
    short: "Photo-first layout with clean grid gallery.",
    pitch:
      "A minimal photo-first website with a clean gallery and inquiry CTA for clients.",
    pages: ["Home", "Portfolio", "Packages", "About", "Contact"],
    bestFor: ["Photographers", "Videographers", "Creators"],
    includes: [...baseIncludes, "Gallery grid", "Package tiers"],
    tags: ["photo", "minimal", "gallery", "packages"],
    accent: { a: "#06b6d4", b: "#a78bfa", c: "#f1f5f9" },
    featuredRank: 32,
    addedAt: "2025-12-28",
  },
  {
    sku: "PORT-003",
    categoryId: "portfolio",
    name: "Illustration Pop",
    style: ["Playful", "Bold"],
    price: money(59),
    short: "Bright playful layout for illustrators and artists.",
    pitch:
      "Made to stand out: bold colors, project cards, and a friendly commission CTA.",
    pages: ["Home", "Work", "Commissions", "About", "Contact"],
    bestFor: ["Illustrators", "Artists", "Commission work"],
    includes: [...baseIncludes, "Commission section", "Project cards"],
    tags: ["illustration", "playful", "bold", "commission"],
    accent: { a: "#f472b6", b: "#22c55e", c: "#f59e0b" },
    featuredRank: 33,
    addedAt: "2026-01-02",
  },
  {
    sku: "PORT-004",
    categoryId: "portfolio",
    name: "Motion Neon",
    style: ["Neon", "Modern"],
    price: money(69),
    short: "Neon creative vibe for motion designers.",
    pitch:
      "A modern neon template for motion design portfolios—great for reels, services, and client inquiries.",
    pages: ["Home", "Reel", "Projects", "Services", "Contact"],
    bestFor: ["Motion designers", "Video editors", "Studios"],
    includes: [...baseIncludes, "Reel highlight section", "Service cards"],
    tags: ["motion", "neon", "portfolio", "reel"],
    accent: { a: "#22c55e", b: "#06b6d4", c: "#a855f7" },
    featuredRank: 34,
    addedAt: "2026-01-12",
  },
  {
    sku: "PORT-005",
    categoryId: "portfolio",
    name: "Writer Editorial",
    style: ["Editorial", "Minimal"],
    price: money(49),
    short: "Editorial blog/portfolio for writers and consultants.",
    pitch:
      "Simple but premium editorial layout for writers: articles list, services, and contact CTA.",
    pages: ["Home", "Articles", "Services", "About", "Contact"],
    bestFor: ["Writers", "Consultants", "Personal brands"],
    includes: [...baseIncludes, "Article list layout", "Bio section"],
    tags: ["writer", "editorial", "minimal", "personal"],
    accent: { a: "#0ea5e9", b: "#111827", c: "#9ca3af" },
    featuredRank: 35,
    addedAt: "2025-12-24",
  },

  // Events & Wedding (5)
  {
    sku: "EVT-001",
    categoryId: "events",
    name: "Wedding Ivory",
    style: ["Elegant", "Luxury"],
    price: money(79),
    short: "Wedding invite microsite with RSVP section.",
    pitch:
      "A classy wedding microsite: schedule, venue map links, dress code, and RSVP CTA (static placeholder).",
    pages: ["Home", "Our Story", "Schedule", "Venue", "RSVP"],
    bestFor: ["Weddings", "Engagement parties", "Private events"],
    includes: [...baseIncludes, "Schedule section", "RSVP section (static)"],
    tags: ["wedding", "elegant", "rsvp", "luxury"],
    accent: { a: "#fde68a", b: "#f472b6", c: "#a78bfa" },
    featuredRank: 36,
    addedAt: "2026-01-03",
  },
  {
    sku: "EVT-002",
    categoryId: "events",
    name: "Conference Pro",
    style: ["Corporate", "Modern"],
    price: money(109),
    short: "Event landing with speakers, agenda, and tickets CTA.",
    pitch:
      "A professional event landing: speakers, agenda blocks, and a ticket CTA. Perfect for conferences and seminars.",
    pages: ["Home", "Speakers", "Agenda", "Sponsors", "Tickets"],
    bestFor: ["Conferences", "Seminars", "Business events"],
    includes: [...baseIncludes, "Speaker cards", "Agenda layout"],
    tags: ["conference", "agenda", "speakers", "tickets"],
    accent: { a: "#2563eb", b: "#06b6d4", c: "#111827" },
    featuredRank: 37,
    addedAt: "2026-01-10",
  },
  {
    sku: "EVT-003",
    categoryId: "events",
    name: "Birthday Pop",
    style: ["Playful", "Bold"],
    price: money(49),
    short: "Fun party invite page with countdown and location.",
    pitch:
      "A playful party invite page. Includes countdown (static look), location info, and a big RSVP CTA.",
    pages: ["Home", "Details", "Gallery", "FAQ", "RSVP"],
    bestFor: ["Birthdays", "Celebrations", "Private invites"],
    includes: [...baseIncludes, "Countdown section (static)", "FAQ section"],
    tags: ["birthday", "party", "playful", "rsvp"],
    accent: { a: "#f97316", b: "#22c55e", c: "#06b6d4" },
    featuredRank: 38,
    addedAt: "2025-12-30",
  },
  {
    sku: "EVT-004",
    categoryId: "events",
    name: "DJ Night Neon",
    style: ["Neon", "Bold"],
    price: money(59),
    short: "Nightlife flyer site with lineup and tickets CTA.",
    pitch:
      "A neon nightlife landing: lineup, venue, and ticket CTA. Great for DJs and club nights.",
    pages: ["Home", "Lineup", "Venue", "Gallery", "Tickets"],
    bestFor: ["DJ events", "Clubs", "Promoters"],
    includes: [...baseIncludes, "Lineup blocks", "Ticket CTA"],
    tags: ["dj", "neon", "nightlife", "tickets"],
    accent: { a: "#a855f7", b: "#06b6d4", c: "#22c55e" },
    featuredRank: 39,
    addedAt: "2026-01-13",
  },
  {
    sku: "EVT-005",
    categoryId: "events",
    name: "Festival Warm",
    style: ["Warm", "Modern"],
    price: money(79),
    short: "Festival landing with schedule blocks and vendor section.",
    pitch:
      "A friendly modern festival page with schedule, map links, and vendor highlights.",
    pages: ["Home", "Schedule", "Vendors", "Map", "Tickets"],
    bestFor: ["Festivals", "Markets", "Community events"],
    includes: [...baseIncludes, "Vendor cards", "Schedule section"],
    tags: ["festival", "warm", "vendors", "tickets"],
    accent: { a: "#22c55e", b: "#f59e0b", c: "#0ea5e9" },
    featuredRank: 40,
    addedAt: "2026-01-06",
  },

  // Mini Shop (5)
  {
    sku: "SHOP-001",
    categoryId: "shop",
    name: "Micro Shop Minimal",
    style: ["Minimal", "Modern"],
    price: money(89),
    short: "Simple mini shop catalogue with featured items and CTA.",
    pitch:
      "A clean mini shop template: featured products, bundles, and social proof. Great for small sellers.",
    pages: ["Home", "Catalog", "Bundles", "FAQ", "Contact"],
    bestFor: ["Small shops", "Instagram sellers", "Handmade goods"],
    includes: [...baseIncludes, "Product card layouts", "Bundle section"],
    tags: ["shop", "minimal", "catalog", "bundles"],
    accent: { a: "#0ea5e9", b: "#22c55e", c: "#111827" },
    featuredRank: 41,
    addedAt: "2026-01-04",
  },
  {
    sku: "SHOP-002",
    categoryId: "shop",
    name: "Beauty Shop Luxe",
    style: ["Luxury", "Elegant"],
    price: money(109),
    short: "Premium cosmetic shop landing with product highlights.",
    pitch:
      "High-end cosmetic shop feel with premium spacing, product highlights, and a clean CTA to buy via DM.",
    pages: ["Home", "Products", "Bundles", "Reviews", "Contact"],
    bestFor: ["Cosmetics", "Skincare", "Beauty brands"],
    includes: [...baseIncludes, "Review strip", "Product highlight sections"],
    tags: ["cosmetics", "luxury", "shop", "reviews"],
    accent: { a: "#f472b6", b: "#a78bfa", c: "#06b6d4" },
    featuredRank: 42,
    addedAt: "2026-01-11",
  },
  {
    sku: "SHOP-003",
    categoryId: "shop",
    name: "Streetwear Neon",
    style: ["Neon", "Bold"],
    price: money(99),
    short: "Streetwear look with drops, sizes, and social CTAs.",
    pitch:
      "Built for drops: featured collection, size guide, and a buy CTA designed for WhatsApp/DM ordering.",
    pages: ["Home", "Drops", "Lookbook", "Size Guide", "Contact"],
    bestFor: ["Streetwear", "Merch", "Limited drops"],
    includes: [...baseIncludes, "Size guide section", "Lookbook layout"],
    tags: ["streetwear", "neon", "drops", "bold"],
    accent: { a: "#22c55e", b: "#a855f7", c: "#06b6d4" },
    featuredRank: 43,
    addedAt: "2026-01-13",
  },
  {
    sku: "SHOP-004",
    categoryId: "shop",
    name: "Coffee Gear Warm",
    style: ["Warm", "Editorial"],
    price: money(79),
    short: "Warm editorial shop landing for small products.",
    pitch:
      "A warm product catalogue style: bundles, shipping info section (static), and product features.",
    pages: ["Home", "Catalog", "Bundles", "Shipping", "Contact"],
    bestFor: ["Coffee gear", "Accessories", "Small product brands"],
    includes: [...baseIncludes, "Shipping info block", "Feature list sections"],
    tags: ["coffee", "warm", "editorial", "shop"],
    accent: { a: "#f59e0b", b: "#f97316", c: "#0ea5e9" },
    featuredRank: 44,
    addedAt: "2025-12-29",
  },
  {
    sku: "SHOP-005",
    categoryId: "shop",
    name: "Craft Market Pop",
    style: ["Playful", "Warm"],
    price: money(59),
    short: "Friendly craft seller site with bundles and story.",
    pitch:
      "A friendly layout for handmade sellers with product cards, bundle offers, and a story section that builds trust.",
    pages: ["Home", "Catalog", "Bundles", "Our Story", "Contact"],
    bestFor: ["Handmade", "Crafts", "Small sellers"],
    includes: [...baseIncludes, "Bundle offers", "Story section"],
    tags: ["craft", "handmade", "warm", "playful"],
    accent: { a: "#22c55e", b: "#fb7185", c: "#f59e0b" },
    featuredRank: 45,
    addedAt: "2026-01-02",
  },

  // Tech & Startup (5)
  {
    sku: "TECH-001",
    categoryId: "tech",
    name: "Midnight SaaS",
    style: ["Modern", "Neon"],
    price: money(119),
    short: "SaaS landing with features, pricing, and waitlist CTA.",
    pitch:
      "A strong SaaS landing: feature highlights, pricing tiers, and a waitlist CTA. Great for MVP launches.",
    pages: ["Home", "Features", "Pricing", "FAQ", "Contact"],
    bestFor: ["SaaS", "Startups", "MVP launches"],
    includes: [...baseIncludes, "Pricing tiers", "Feature sections"],
    tags: ["saas", "neon", "pricing", "waitlist"],
    accent: { a: "#a855f7", b: "#06b6d4", c: "#22c55e" },
    featuredRank: 46,
    addedAt: "2026-01-14",
  },
  {
    sku: "TECH-002",
    categoryId: "tech",
    name: "Startup Minimal",
    style: ["Minimal", "Corporate"],
    price: money(99),
    short: "Clean corporate landing with credibility blocks.",
    pitch:
      "A clean, investor-friendly landing: problem/solution, metrics, and a clear CTA for demos.",
    pages: ["Home", "Solution", "Metrics", "Pricing", "Contact"],
    bestFor: ["B2B startups", "Consulting", "SaaS"],
    includes: [...baseIncludes, "Metrics strip", "Demo CTA"],
    tags: ["startup", "minimal", "b2b", "metrics"],
    accent: { a: "#2563eb", b: "#111827", c: "#06b6d4" },
    featuredRank: 47,
    addedAt: "2026-01-08",
  },
  {
    sku: "TECH-003",
    categoryId: "tech",
    name: "App Launch Pop",
    style: ["Playful", "Modern"],
    price: money(79),
    short: "App landing with screenshots strip (mock) and CTA.",
    pitch:
      "Made for mobile apps: highlights, mock screenshot strip, and a ‘Get early access’ CTA.",
    pages: ["Home", "Features", "Screens", "FAQ", "Contact"],
    bestFor: ["Mobile apps", "Side projects", "Waitlists"],
    includes: [...baseIncludes, "Screenshot strip (mock)", "Waitlist CTA"],
    tags: ["app", "playful", "modern", "launch"],
    accent: { a: "#f97316", b: "#06b6d4", c: "#a78bfa" },
    featuredRank: 48,
    addedAt: "2026-01-03",
  },
  {
    sku: "TECH-004",
    categoryId: "tech",
    name: "Agency Deck",
    style: ["Corporate", "Editorial"],
    price: money(109),
    short: "Agency website with case studies and service packages.",
    pitch:
      "A premium agency layout: service packages, case studies, and a CTA for booking a call.",
    pages: ["Home", "Services", "Case Studies", "Process", "Contact"],
    bestFor: ["Agencies", "Freelancers", "Studios"],
    includes: [...baseIncludes, "Process timeline", "Case study layout"],
    tags: ["agency", "corporate", "case-study", "process"],
    accent: { a: "#0ea5e9", b: "#a855f7", c: "#111827" },
    featuredRank: 49,
    addedAt: "2026-01-10",
  },
  {
    sku: "TECH-005",
    categoryId: "tech",
    name: "Crypto Neon Onepager",
    style: ["Neon", "Bold"],
    price: money(59),
    short: "Neon one-page landing for crypto/web3 projects.",
    pitch:
      "A punchy neon one-pager with sections for benefits, token utility (generic), and community CTA.",
    pages: ["Home", "Utility", "Roadmap", "Community", "Contact"],
    bestFor: ["Web3", "Communities", "Token projects"],
    includes: [...baseIncludes, "Roadmap section", "Community CTA"],
    tags: ["crypto", "neon", "bold", "community"],
    accent: { a: "#22c55e", b: "#06b6d4", c: "#a855f7" },
    featuredRank: 50,
    addedAt: "2025-12-26",
  },

  // NEW Restaurant & Cafe (6)
  {
    sku: "FOOD-006",
    categoryId: "food",
    name: "Pizza Palace Bold",
    style: ["Bold", "Modern"],
    price: money(89),
    short: "Bold pizzeria template with fire-oven appeal and strong visuals.",
    pitch:
      "Built for pizzerias that want to stand out. Dark theme with neon accents, signature pizzas grid, and strong order CTA.",
    pages: ["Home", "Menu", "Specials", "Location", "Order"],
    bestFor: ["Pizzerias", "Italian restaurants", "Fire-oven cooking"],
    includes: [...baseIncludes, "Menu grid layout", "Location section"],
    tags: ["pizza", "bold", "modern", "italian"],
    accent: { a: "#E63946", b: "#F25C54", c: "#F4F1DE" },
    featuredRank: 51,
    addedAt: "2026-03-19",
  },
  {
    sku: "FOOD-007",
    categoryId: "food",
    name: "Tea Garden Elegant",
    style: ["Elegant", "Minimal"],
    price: money(69),
    short: "Elegant minimal template for tea houses and cafes.",
    pitch:
      "A serene, premium tea house template with soft colors, menu sections, and reservation flow.",
    pages: ["Home", "Tea Menu", "About", "Gallery", "Contact"],
    bestFor: ["Tea houses", "Zen cafes", "Specialty tea"],
    includes: [...baseIncludes, "Tea menu layout", "Calm aesthetics"],
    tags: ["tea", "elegant", "minimal", "zen"],
    accent: { a: "#8B7E74", b: "#C9B8A8", c: "#E8DFD8" },
    featuredRank: 52,
    addedAt: "2026-03-19",
  },
  {
    sku: "FOOD-008",
    categoryId: "food",
    name: "Burger Joint Neon",
    style: ["Neon", "Playful"],
    price: money(79),
    short: "Neon playful burger restaurant with bold colors and appetite appeal.",
    pitch:
      "High-energy burger joint template with neon lights, combo deals section, and fun vibe.",
    pages: ["Home", "Burgers", "Combos", "Location", "Order"],
    bestFor: ["Burger joints", "Fast casual", "Late-night eateries"],
    includes: [...baseIncludes, "Combo deals section", "Neon aesthetics"],
    tags: ["burger", "neon", "playful", "fast-food"],
    accent: { a: "#FF3366", b: "#33FF99", c: "#3366FF" },
    featuredRank: 53,
    addedAt: "2026-03-19",
  },
  {
    sku: "FOOD-009",
    categoryId: "food",
    name: "Fine Dining Luxe",
    style: ["Luxury", "Editorial"],
    price: money(129),
    short: "Luxury editorial template for fine dining restaurants.",
    pitch:
      "Premium fine dining layout with tasting menu, wine pairing, and sophisticated reservation CTA.",
    pages: ["Home", "Tasting Menu", "Wine List", "Chef", "Reservations"],
    bestFor: ["Fine dining", "Michelin restaurants", "Premium eateries"],
    includes: [...baseIncludes, "Tasting menu layout", "Wine pairing section"],
    tags: ["fine-dining", "luxury", "editorial", "premium"],
    accent: { a: "#1A1A1D", b: "#C3073F", c: "#E8B4B8" },
    featuredRank: 54,
    addedAt: "2026-03-19",
  },
  {
    sku: "FOOD-010",
    categoryId: "food",
    name: "Taco Fiesta",
    style: ["Warm", "Playful"],
    price: money(69),
    short: "Warm playful Mexican restaurant with vibrant colors.",
    pitch:
      "Festive taco restaurant template with colorful design, menu highlights, and catering info.",
    pages: ["Home", "Tacos", "Specials", "Catering", "Contact"],
    bestFor: ["Taco shops", "Mexican food", "Catering"],
    includes: [...baseIncludes, "Specials section", "Catering CTA"],
    tags: ["tacos", "mexican", "warm", "playful"],
    accent: { a: "#FF6B35", b: "#F7931E", c: "#FDC500" },
    featuredRank: 55,
    addedAt: "2026-03-19",
  },
  {
    sku: "FOOD-011",
    categoryId: "food",
    name: "Breakfast Club Warm",
    style: ["Modern", "Warm"],
    price: money(79),
    short: "Modern warm breakfast cafe with cozy morning vibes.",
    pitch:
      "Perfect for breakfast spots: morning specials, coffee menu, and friendly reservation section.",
    pages: ["Home", "Breakfast Menu", "Coffee", "Brunch", "Contact"],
    bestFor: ["Breakfast cafes", "Brunch spots", "Coffee shops"],
    includes: [...baseIncludes, "Breakfast menu layout", "Coffee section"],
    tags: ["breakfast", "brunch", "warm", "modern"],
    accent: { a: "#F4A259", b: "#BC4B51", c: "#8CB369" },
    featuredRank: 56,
    addedAt: "2026-03-19",
  },

  // NEW Real Estate (6)
  {
    sku: "RE-006",
    categoryId: "realestate",
    name: "Beach Condo Luxe",
    style: ["Luxury", "Modern"],
    price: money(139),
    short: "Luxury modern template for beach properties and condos.",
    pitch:
      "High-end beach property landing with ocean views, amenities showcase, and inquiry CTA.",
    pages: ["Home", "Gallery", "Amenities", "Beach Access", "Contact"],
    bestFor: ["Beach condos", "Coastal properties", "Resort living"],
    includes: [...baseIncludes, "Beach amenities section", "Gallery showcase"],
    tags: ["beach", "luxury", "condo", "modern"],
    accent: { a: "#0077B6", b: "#00B4D8", c: "#90E0EF" },
    featuredRank: 57,
    addedAt: "2026-03-19",
  },
  {
    sku: "RE-007",
    categoryId: "realestate",
    name: "Office Space Pro",
    style: ["Corporate", "Minimal"],
    price: money(119),
    short: "Corporate minimal template for commercial real estate.",
    pitch:
      "Professional commercial space listing with floor plans, specs, and leasing inquiry form.",
    pages: ["Home", "Specs", "Floor Plans", "Location", "Inquire"],
    bestFor: ["Office spaces", "Commercial real estate", "Co-working"],
    includes: [...baseIncludes, "Floor plan viewer", "Specs table"],
    tags: ["commercial", "office", "corporate", "minimal"],
    accent: { a: "#2B2D42", b: "#8D99AE", c: "#EDF2F4" },
    featuredRank: 58,
    addedAt: "2026-03-19",
  },
  {
    sku: "RE-008",
    categoryId: "realestate",
    name: "Tiny Home Minimal",
    style: ["Minimal", "Editorial"],
    price: money(89),
    short: "Minimal editorial template for tiny homes and small living.",
    pitch:
      "Clean tiny home showcase with gallery, sustainability features, and inquiry CTA.",
    pages: ["Home", "Gallery", "Features", "Sustainability", "Contact"],
    bestFor: ["Tiny homes", "Eco living", "Minimalist properties"],
    includes: [...baseIncludes, "Feature highlights", "Sustainability info"],
    tags: ["tiny-home", "minimal", "eco", "editorial"],
    accent: { a: "#8B7E74", b: "#A9927D", c: "#E8DFD8" },
    featuredRank: 59,
    addedAt: "2026-03-19",
  },
  {
    sku: "RE-009",
    categoryId: "realestate",
    name: "Mountain Retreat",
    style: ["Warm", "Elegant"],
    price: money(129),
    short: "Warm elegant template for mountain properties and retreats.",
    pitch:
      "Perfect for mountain cabins: nature views, cozy features, and booking inquiry section.",
    pages: ["Home", "Property", "Views", "Activities", "Contact"],
    bestFor: ["Mountain cabins", "Retreats", "Vacation rentals"],
    includes: [...baseIncludes, "View showcase", "Activities section"],
    tags: ["mountain", "retreat", "warm", "elegant"],
    accent: { a: "#6B705C", b: "#A5A58D", c: "#CB997E" },
    featuredRank: 60,
    addedAt: "2026-03-19",
  },
  {
    sku: "RE-010",
    categoryId: "realestate",
    name: "Urban Loft Bold",
    style: ["Bold", "Modern"],
    price: money(109),
    short: "Bold modern template for urban lofts and city living.",
    pitch:
      "Dynamic urban loft showcase with industrial vibes, location perks, and inquiry form.",
    pages: ["Home", "Loft Features", "Neighborhood", "Gallery", "Contact"],
    bestFor: ["Urban lofts", "City apartments", "Modern living"],
    includes: [...baseIncludes, "Neighborhood highlights", "Industrial design"],
    tags: ["loft", "urban", "bold", "modern"],
    accent: { a: "#EE6C4D", b: "#293241", c: "#98C1D9" },
    featuredRank: 61,
    addedAt: "2026-03-19",
  },
  {
    sku: "RE-011",
    categoryId: "realestate",
    name: "Real Estate Agency Corp",
    style: ["Corporate", "Professional"],
    price: money(129),
    short: "Corporate professional template for real estate agencies.",
    pitch:
      "Full-service agency website with team profiles, listings grid, and lead capture system.",
    pages: ["Home", "Listings", "Team", "Services", "Contact"],
    bestFor: ["Real estate agencies", "Broker firms", "Property managers"],
    includes: [...baseIncludes, "Team profiles", "Listings grid"],
    tags: ["agency", "corporate", "professional", "broker"],
    accent: { a: "#003049", b: "#D62828", c: "#F77F00" },
    featuredRank: 62,
    addedAt: "2026-03-19",
  },

  // NEW Fitness & Wellness (6)
  {
    sku: "FIT-006",
    categoryId: "fitness",
    name: "Boxing Bold",
    style: ["Bold", "Modern"],
    price: money(99),
    short: "Bold modern template for boxing gyms and fight clubs.",
    pitch:
      "High-energy boxing gym template with class schedule, trainer profiles, and membership CTA.",
    pages: ["Home", "Classes", "Trainers", "Schedule", "Join Now"],
    bestFor: ["Boxing gyms", "Fight clubs", "Combat sports"],
    includes: [...baseIncludes, "Class schedule", "Trainer bios"],
    tags: ["boxing", "bold", "modern", "combat"],
    accent: { a: "#DC2626", b: "#1F2937", c: "#F59E0B" },
    featuredRank: 63,
    addedAt: "2026-03-19",
  },
  {
    sku: "FIT-007",
    categoryId: "fitness",
    name: "Dance Studio Playful",
    style: ["Playful", "Modern"],
    price: money(79),
    short: "Playful modern template for dance studios and classes.",
    pitch:
      "Vibrant dance studio site with class types, instructor showcase, and trial class CTA.",
    pages: ["Home", "Classes", "Instructors", "Schedule", "Join"],
    bestFor: ["Dance studios", "Dance schools", "Movement classes"],
    includes: [...baseIncludes, "Class types grid", "Instructor profiles"],
    tags: ["dance", "playful", "modern", "movement"],
    accent: { a: "#EC4899", b: "#8B5CF6", c: "#F59E0B" },
    featuredRank: 64,
    addedAt: "2026-03-19",
  },
  {
    sku: "FIT-008",
    categoryId: "fitness",
    name: "Meditation Calm",
    style: ["Minimal", "Warm"],
    price: money(69),
    short: "Minimal warm template for meditation centers and mindfulness.",
    pitch:
      "Peaceful meditation center site with class info, benefits section, and booking CTA.",
    pages: ["Home", "Sessions", "Benefits", "Teachers", "Book"],
    bestFor: ["Meditation centers", "Mindfulness studios", "Wellness"],
    includes: [...baseIncludes, "Benefits highlights", "Session types"],
    tags: ["meditation", "minimal", "warm", "mindfulness"],
    accent: { a: "#6366F1", b: "#A78BFA", c: "#DDD6FE" },
    featuredRank: 65,
    addedAt: "2026-03-19",
  },
  {
    sku: "FIT-009",
    categoryId: "fitness",
    name: "CrossFit Neon",
    style: ["Neon", "Bold"],
    price: money(99),
    short: "Neon bold template for CrossFit gyms and high-intensity training.",
    pitch:
      "Intense CrossFit gym template with WODs, community vibe, and membership signup.",
    pages: ["Home", "WODs", "Community", "Pricing", "Join"],
    bestFor: ["CrossFit gyms", "HIIT studios", "Functional fitness"],
    includes: [...baseIncludes, "WOD section", "Community highlights"],
    tags: ["crossfit", "neon", "bold", "hiit"],
    accent: { a: "#10B981", b: "#06B6D4", c: "#F59E0B" },
    featuredRank: 66,
    addedAt: "2026-03-19",
  },
  {
    sku: "FIT-010",
    categoryId: "fitness",
    name: "Personal Trainer",
    style: ["Modern", "Editorial"],
    price: money(89),
    short: "Modern editorial template for personal trainers and coaches.",
    pitch:
      "Professional trainer site with transformation stories, packages, and consultation CTA.",
    pages: ["Home", "About", "Results", "Packages", "Contact"],
    bestFor: ["Personal trainers", "Fitness coaches", "Online coaching"],
    includes: [...baseIncludes, "Transformation showcase", "Package tiers"],
    tags: ["trainer", "modern", "editorial", "coaching"],
    accent: { a: "#059669", b: "#0891B2", c: "#1E293B" },
    featuredRank: 67,
    addedAt: "2026-03-19",
  },
  {
    sku: "FIT-011",
    categoryId: "fitness",
    name: "Wellness Retreat Luxe",
    style: ["Luxury", "Elegant"],
    price: money(149),
    short: "Luxury elegant template for wellness retreats and spas.",
    pitch:
      "Premium wellness retreat with program details, accommodations, and booking system.",
    pages: ["Home", "Programs", "Accommodations", "Gallery", "Book"],
    bestFor: ["Wellness retreats", "Yoga retreats", "Spa resorts"],
    includes: [...baseIncludes, "Program cards", "Accommodation showcase"],
    tags: ["retreat", "luxury", "elegant", "wellness"],
    accent: { a: "#D97706", b: "#059669", c: "#0EA5E9" },
    featuredRank: 68,
    addedAt: "2026-03-19",
  },

  // NEW Beauty Salon & Spa (6)
  {
    sku: "BEAUTY-006",
    categoryId: "beauty",
    name: "Makeup Artist Luxe",
    style: ["Luxury", "Elegant"],
    price: money(99),
    short: "Luxury elegant template for makeup artists and beauty services.",
    pitch:
      "Premium makeup artist portfolio with services, gallery, and booking CTA.",
    pages: ["Home", "Services", "Portfolio", "Pricing", "Book"],
    bestFor: ["Makeup artists", "Bridal makeup", "Beauty services"],
    includes: [...baseIncludes, "Portfolio gallery", "Service menu"],
    tags: ["makeup", "luxury", "elegant", "beauty"],
    accent: { a: "#BE185D", b: "#EC4899", c: "#FDF2F8" },
    featuredRank: 69,
    addedAt: "2026-03-19",
  },
  {
    sku: "BEAUTY-007",
    categoryId: "beauty",
    name: "Men's Spa Bold",
    style: ["Bold", "Modern"],
    price: money(89),
    short: "Bold modern template for men's spas and grooming.",
    pitch:
      "Masculine spa template with grooming services, packages, and membership options.",
    pages: ["Home", "Services", "Packages", "Membership", "Book"],
    bestFor: ["Men's spas", "Grooming lounges", "Barber spas"],
    includes: [...baseIncludes, "Service packages", "Membership section"],
    tags: ["mens-spa", "bold", "modern", "grooming"],
    accent: { a: "#1E3A8A", b: "#3B82F6", c: "#DBEAFE" },
    featuredRank: 70,
    addedAt: "2026-03-19",
  },
  {
    sku: "BEAUTY-008",
    categoryId: "beauty",
    name: "Hair Extension Minimal",
    style: ["Minimal", "Elegant"],
    price: money(99),
    short: "Minimal elegant template for hair extensions and styling.",
    pitch:
      "Clean hair extension studio with types, care guide, and consultation booking.",
    pages: ["Home", "Extensions", "Care Guide", "Gallery", "Consult"],
    bestFor: ["Hair extensions", "Hair studios", "Premium styling"],
    includes: [...baseIncludes, "Extension types", "Care information"],
    tags: ["hair", "extensions", "minimal", "elegant"],
    accent: { a: "#92400E", b: "#D97706", c: "#FEF3C7" },
    featuredRank: 71,
    addedAt: "2026-03-19",
  },
  {
    sku: "BEAUTY-009",
    categoryId: "beauty",
    name: "Brow Bar Playful",
    style: ["Playful", "Modern"],
    price: money(69),
    short: "Playful modern template for brow bars and lash studios.",
    pitch:
      "Fun brow bar site with services, before/after gallery, and quick booking.",
    pages: ["Home", "Services", "Gallery", "Pricing", "Book Now"],
    bestFor: ["Brow bars", "Lash studios", "Beauty bars"],
    includes: [...baseIncludes, "Before/after gallery", "Quick booking"],
    tags: ["brows", "playful", "modern", "lashes"],
    accent: { a: "#DB2777", b: "#F472B6", c: "#FCE7F3" },
    featuredRank: 72,
    addedAt: "2026-03-19",
  },
  {
    sku: "BEAUTY-010",
    categoryId: "beauty",
    name: "Tattoo Studio Neon",
    style: ["Neon", "Bold"],
    price: money(89),
    short: "Neon bold template for tattoo studios and artists.",
    pitch:
      "Edgy tattoo studio with artist portfolios, flash designs, and consultation booking.",
    pages: ["Home", "Artists", "Flash", "Gallery", "Book"],
    bestFor: ["Tattoo studios", "Tattoo artists", "Body art"],
    includes: [...baseIncludes, "Artist portfolios", "Flash gallery"],
    tags: ["tattoo", "neon", "bold", "art"],
    accent: { a: "#DC2626", b: "#8B5CF6", c: "#22D3EE" },
    featuredRank: 73,
    addedAt: "2026-03-19",
  },
  {
    sku: "BEAUTY-011",
    categoryId: "beauty",
    name: "Med Spa Corp",
    style: ["Corporate", "Minimal"],
    price: money(119),
    short: "Corporate minimal template for medical spas and aesthetics.",
    pitch:
      "Professional medical spa with treatments, credentials, and consultation CTA.",
    pages: ["Home", "Treatments", "Credentials", "Results", "Consult"],
    bestFor: ["Medical spas", "Aesthetic clinics", "Dermatology"],
    includes: [...baseIncludes, "Treatment details", "Credentials display"],
    tags: ["med-spa", "corporate", "minimal", "medical"],
    accent: { a: "#0F766E", b: "#14B8A6", c: "#CCFBF1" },
    featuredRank: 74,
    addedAt: "2026-03-19",
  },

  // NEW Local Services (6)
  {
    sku: "SERV-006",
    categoryId: "services",
    name: "Locksmith Pro",
    style: ["Corporate", "Bold"],
    price: money(89),
    short: "Corporate bold template for locksmith and security services.",
    pitch:
      "Trustworthy locksmith site with 24/7 emergency callout, services, and quick contact.",
    pages: ["Home", "Services", "Emergency", "Areas", "Call Now"],
    bestFor: ["Locksmiths", "Security services", "Emergency services"],
    includes: [...baseIncludes, "Emergency banner", "Service areas map"],
    tags: ["locksmith", "security", "corporate", "bold"],
    accent: { a: "#CA8A04", b: "#EAB308", c: "#FEF9C3" },
    featuredRank: 75,
    addedAt: "2026-03-19",
  },
  {
    sku: "SERV-007",
    categoryId: "services",
    name: "Landscaping Warm",
    style: ["Warm", "Modern"],
    price: money(79),
    short: "Warm modern template for landscaping and garden services.",
    pitch:
      "Friendly landscaping site with services, project gallery, and free quote CTA.",
    pages: ["Home", "Services", "Projects", "About", "Get Quote"],
    bestFor: ["Landscaping", "Garden design", "Lawn care"],
    includes: [...baseIncludes, "Project gallery", "Quote form"],
    tags: ["landscaping", "warm", "modern", "garden"],
    accent: { a: "#16A34A", b: "#84CC16", c: "#ECFCCB" },
    featuredRank: 76,
    addedAt: "2026-03-19",
  },
  {
    sku: "SERV-008",
    categoryId: "services",
    name: "Electrician Bold",
    style: ["Bold", "Corporate"],
    price: money(89),
    short: "Bold corporate template for electricians and electrical services.",
    pitch:
      "Professional electrician site with services, emergency callout, and instant quote.",
    pages: ["Home", "Services", "Emergency", "Reviews", "Contact"],
    bestFor: ["Electricians", "Electrical contractors", "Emergency repairs"],
    includes: [...baseIncludes, "Emergency section", "Review highlights"],
    tags: ["electrician", "bold", "corporate", "emergency"],
    accent: { a: "#2563EB", b: "#FBBF24", c: "#DBEAFE" },
    featuredRank: 77,
    addedAt: "2026-03-19",
  },
  {
    sku: "SERV-009",
    categoryId: "services",
    name: "Plumbing Emergency",
    style: ["Modern", "Bold"],
    price: money(89),
    short: "Modern bold template for plumbers and emergency plumbing.",
    pitch:
      "Fast-action plumber site with 24/7 emergency banner, services, and quick call CTA.",
    pages: ["Home", "Services", "Emergency", "Pricing", "Call Now"],
    bestFor: ["Plumbers", "Emergency plumbing", "Drain services"],
    includes: [...baseIncludes, "24/7 emergency banner", "Pricing guide"],
    tags: ["plumbing", "modern", "bold", "emergency"],
    accent: { a: "#0284C7", b: "#0EA5E9", c: "#E0F2FE" },
    featuredRank: 78,
    addedAt: "2026-03-19",
  },
  {
    sku: "SERV-010",
    categoryId: "services",
    name: "Moving Company",
    style: ["Corporate", "Modern"],
    price: money(99),
    short: "Corporate modern template for moving companies and movers.",
    pitch:
      "Professional moving company with services, free quote calculator, and booking system.",
    pages: ["Home", "Services", "Quote", "Reviews", "Book"],
    bestFor: ["Moving companies", "Relocation services", "Storage"],
    includes: [...baseIncludes, "Quote calculator", "Booking flow"],
    tags: ["moving", "corporate", "modern", "relocation"],
    accent: { a: "#DC2626", b: "#F59E0B", c: "#FEF3C7" },
    featuredRank: 79,
    addedAt: "2026-03-19",
  },
  {
    sku: "SERV-011",
    categoryId: "services",
    name: "Pet Grooming Playful",
    style: ["Playful", "Warm"],
    price: money(79),
    short: "Playful warm template for pet grooming and pet care.",
    pitch:
      "Friendly pet grooming site with services, packages, and online booking.",
    pages: ["Home", "Services", "Packages", "Gallery", "Book"],
    bestFor: ["Pet grooming", "Dog salons", "Pet spas"],
    includes: [...baseIncludes, "Service packages", "Pet gallery"],
    tags: ["pet-grooming", "playful", "warm", "pets"],
    accent: { a: "#F97316", b: "#FB923C", c: "#FFEDD5" },
    featuredRank: 80,
    addedAt: "2026-03-19",
  },
];
