export const STYLES = [
  "Modern",
  "Minimal",
  "Bold",
  "Elegant",
  "Playful",
  "Corporate",
  "Luxury",
  "Editorial",
  "Neon",
  "Warm",
];

export const CATEGORIES = [
  { id: "food", name: "Restaurant & Cafe", blurb: "Menus, bookings, promos, delivery CTA." },
  { id: "realestate", name: "Real Estate", blurb: "Listings, agents, lead capture, trust." },
  { id: "fitness", name: "Fitness & Wellness", blurb: "Programs, schedules, memberships, results." },
  { id: "beauty", name: "Beauty Salon & Spa", blurb: "Services, pricing, appointments, gallery." },
  { id: "services", name: "Local Services", blurb: "Handyman, cleaning, HVAC, quick quotes." },
];

const money = (n) => Math.round(n);

const baseIncludes = [
  "Responsive layout (mobile-first)",
  "Modern sections & spacing",
  "SEO-friendly structure",
  "Fast load (no backend)",
  "Easy color + font swap",
];

const pagesCommon = ["Home", "About", "Services", "Contact"];

/**
 * 31 catalogue items (5 categories with live templates)
 * Each item has a corresponding HTML template in the catalogue folder.
 */
export const ITEMS = [
  {
    sku: "FOOD-005",
    categoryId: "food",
    name: "Bakery Luxe",
    style: ["Luxury", "Elegant"],
    price: money(99),
    short: "Soft luxury look for bakeries and dessert brands.",
    pitch:
      "A premium bakery template: hero, best-sellers, seasonal box, and a strong order CTA. Perfect for brands that sell gift boxes.",
    pages: ["Home", "Best Sellers", "Seasonal", "FAQ", "Contact"],
    bestFor: ["Bakeries", "Desserts", "Gift boxes"],
    includes: [...baseIncludes, "Best-seller cards", "FAQ accordion (static)"],
    tags: ["luxury", "bakery", "elegant", "gift"],
    accent: { a: "#f472b6", b: "#a78bfa", c: "#fde68a" },
    featuredRank: 1,
    addedAt: "2026-01-14",
  },
  {
    sku: "FOOD-006",
    categoryId: "food",
    name: "Pizza Palace Bold",
    style: ["Bold", "Modern"],
    price: money(89),
    short: "Bold pizzeria template with fire-oven appeal and strong visuals.",
    pitch:
      "Built for pizzerias that want to stand out. Dark theme with neon accents, signature pizzas grid, and strong order CTA.",
    pages: ["Home", "Menu", "Specials", "Location", "Order"],
    bestFor: ["Pizzerias", "Italian restaurants", "Fire-oven cooking"],
    includes: [...baseIncludes, "Menu grid layout", "Location section"],
    tags: ["pizza", "bold", "modern", "italian"],
    accent: { a: "#E63946", b: "#F25C54", c: "#F4F1DE" },
    featuredRank: 51,
    addedAt: "2026-03-19",
  },
  {
    sku: "FOOD-007",
    categoryId: "food",
    name: "Tea Garden Elegant",
    style: ["Elegant", "Minimal"],
    price: money(69),
    short: "Elegant minimal template for tea houses and cafes.",
    pitch:
      "A serene, premium tea house template with soft colors, menu sections, and reservation flow.",
    pages: ["Home", "Tea Menu", "About", "Gallery", "Contact"],
    bestFor: ["Tea houses", "Zen cafes", "Specialty tea"],
    includes: [...baseIncludes, "Tea menu layout", "Calm aesthetics"],
    tags: ["tea", "elegant", "minimal", "zen"],
    accent: { a: "#8B7E74", b: "#C9B8A8", c: "#E8DFD8" },
    featuredRank: 52,
    addedAt: "2026-03-19",
  },
  {
    sku: "FOOD-008",
    categoryId: "food",
    name: "Burger Joint Neon",
    style: ["Neon", "Playful"],
    price: money(79),
    short: "Neon playful burger restaurant with bold colors and appetite appeal.",
    pitch:
      "High-energy burger joint template with neon lights, combo deals section, and fun vibe.",
    pages: ["Home", "Burgers", "Combos", "Location", "Order"],
    bestFor: ["Burger joints", "Fast casual", "Late-night eateries"],
    includes: [...baseIncludes, "Combo deals section", "Neon aesthetics"],
    tags: ["burger", "neon", "playful", "fast-food"],
    accent: { a: "#FF3366", b: "#33FF99", c: "#3366FF" },
    featuredRank: 53,
    addedAt: "2026-03-19",
  },
  {
    sku: "FOOD-009",
    categoryId: "food",
    name: "Fine Dining Luxe",
    style: ["Luxury", "Editorial"],
    price: money(129),
    short: "Luxury editorial template for fine dining restaurants.",
    pitch:
      "Premium fine dining layout with tasting menu, wine pairing, and sophisticated reservation CTA.",
    pages: ["Home", "Tasting Menu", "Wine List", "Chef", "Reservations"],
    bestFor: ["Fine dining", "Michelin restaurants", "Premium eateries"],
    includes: [...baseIncludes, "Tasting menu layout", "Wine pairing section"],
    tags: ["fine-dining", "luxury", "editorial", "premium"],
    accent: { a: "#1A1A1D", b: "#C3073F", c: "#E8B4B8" },
    featuredRank: 54,
    addedAt: "2026-03-19",
  },
  {
    sku: "FOOD-010",
    categoryId: "food",
    name: "Taco Fiesta",
    style: ["Warm", "Playful"],
    price: money(69),
    short: "Warm playful Mexican restaurant with vibrant colors.",
    pitch:
      "Festive taco restaurant template with colorful design, menu highlights, and catering info.",
    pages: ["Home", "Tacos", "Specials", "Catering", "Contact"],
    bestFor: ["Taco shops", "Mexican food", "Catering"],
    includes: [...baseIncludes, "Specials section", "Catering CTA"],
    tags: ["tacos", "mexican", "warm", "playful"],
    accent: { a: "#FF6B35", b: "#F7931E", c: "#FDC500" },
    featuredRank: 55,
    addedAt: "2026-03-19",
  },
  {
    sku: "FOOD-011",
    categoryId: "food",
    name: "Breakfast Club Warm",
    style: ["Modern", "Warm"],
    price: money(79),
    short: "Modern warm breakfast cafe with cozy morning vibes.",
    pitch:
      "Perfect for breakfast spots: morning specials, coffee menu, and friendly reservation section.",
    pages: ["Home", "Breakfast Menu", "Coffee", "Brunch", "Contact"],
    bestFor: ["Breakfast cafes", "Brunch spots", "Coffee shops"],
    includes: [...baseIncludes, "Breakfast menu layout", "Coffee section"],
    tags: ["breakfast", "brunch", "warm", "modern"],
    accent: { a: "#F4A259", b: "#BC4B51", c: "#8CB369" },
    featuredRank: 56,
    addedAt: "2026-03-19",
  },
  {
    sku: "RE-006",
    categoryId: "realestate",
    name: "Beach Condo Luxe",
    style: ["Luxury", "Modern"],
    price: money(139),
    short: "Luxury modern template for beach properties and condos.",
    pitch:
      "High-end beach property landing with ocean views, amenities showcase, and inquiry CTA.",
    pages: ["Home", "Gallery", "Amenities", "Beach Access", "Contact"],
    bestFor: ["Beach condos", "Coastal properties", "Resort living"],
    includes: [...baseIncludes, "Beach amenities section", "Gallery showcase"],
    tags: ["beach", "luxury", "condo", "modern"],
    accent: { a: "#0077B6", b: "#00B4D8", c: "#90E0EF" },
    featuredRank: 57,
    addedAt: "2026-03-19",
  },
  {
    sku: "RE-007",
    categoryId: "realestate",
    name: "Office Space Pro",
    style: ["Corporate", "Minimal"],
    price: money(119),
    short: "Corporate minimal template for commercial real estate.",
    pitch:
      "Professional commercial space listing with floor plans, specs, and leasing inquiry form.",
    pages: ["Home", "Specs", "Floor Plans", "Location", "Inquire"],
    bestFor: ["Office spaces", "Commercial real estate", "Co-working"],
    includes: [...baseIncludes, "Floor plan viewer", "Specs table"],
    tags: ["commercial", "office", "corporate", "minimal"],
    accent: { a: "#2B2D42", b: "#8D99AE", c: "#EDF2F4" },
    featuredRank: 58,
    addedAt: "2026-03-19",
  },
  {
    sku: "RE-008",
    categoryId: "realestate",
    name: "Tiny Home Minimal",
    style: ["Minimal", "Editorial"],
    price: money(89),
    short: "Minimal editorial template for tiny homes and small living.",
    pitch:
      "Clean tiny home showcase with gallery, sustainability features, and inquiry CTA.",
    pages: ["Home", "Gallery", "Features", "Sustainability", "Contact"],
    bestFor: ["Tiny homes", "Eco living", "Minimalist properties"],
    includes: [...baseIncludes, "Feature highlights", "Sustainability info"],
    tags: ["tiny-home", "minimal", "eco", "editorial"],
    accent: { a: "#8B7E74", b: "#A9927D", c: "#E8DFD8" },
    featuredRank: 59,
    addedAt: "2026-03-19",
  },
  {
    sku: "RE-009",
    categoryId: "realestate",
    name: "Mountain Retreat",
    style: ["Warm", "Elegant"],
    price: money(129),
    short: "Warm elegant template for mountain properties and retreats.",
    pitch:
      "Perfect for mountain cabins: nature views, cozy features, and booking inquiry section.",
    pages: ["Home", "Property", "Views", "Activities", "Contact"],
    bestFor: ["Mountain cabins", "Retreats", "Vacation rentals"],
    includes: [...baseIncludes, "View showcase", "Activities section"],
    tags: ["mountain", "retreat", "warm", "elegant"],
    accent: { a: "#6B705C", b: "#A5A58D", c: "#CB997E" },
    featuredRank: 60,
    addedAt: "2026-03-19",
  },
  {
    sku: "RE-010",
    categoryId: "realestate",
    name: "Urban Loft Bold",
    style: ["Bold", "Modern"],
    price: money(109),
    short: "Bold modern template for urban lofts and city living.",
    pitch:
      "Dynamic urban loft showcase with industrial vibes, location perks, and inquiry form.",
    pages: ["Home", "Loft Features", "Neighborhood", "Gallery", "Contact"],
    bestFor: ["Urban lofts", "City apartments", "Modern living"],
    includes: [...baseIncludes, "Neighborhood highlights", "Industrial design"],
    tags: ["loft", "urban", "bold", "modern"],
    accent: { a: "#EE6C4D", b: "#293241", c: "#98C1D9" },
    featuredRank: 61,
    addedAt: "2026-03-19",
  },
  {
    sku: "RE-011",
    categoryId: "realestate",
    name: "Real Estate Agency Corp",
    style: ["Corporate", "Professional"],
    price: money(129),
    short: "Corporate professional template for real estate agencies.",
    pitch:
      "Full-service agency website with team profiles, listings grid, and lead capture system.",
    pages: ["Home", "Listings", "Team", "Services", "Contact"],
    bestFor: ["Real estate agencies", "Broker firms", "Property managers"],
    includes: [...baseIncludes, "Team profiles", "Listings grid"],
    tags: ["agency", "corporate", "professional", "broker"],
    accent: { a: "#003049", b: "#D62828", c: "#F77F00" },
    featuredRank: 62,
    addedAt: "2026-03-19",
  },
  {
    sku: "FIT-006",
    categoryId: "fitness",
    name: "Boxing Bold",
    style: ["Bold", "Modern"],
    price: money(99),
    short: "Bold modern template for boxing gyms and fight clubs.",
    pitch:
      "High-energy boxing gym template with class schedule, trainer profiles, and membership CTA.",
    pages: ["Home", "Classes", "Trainers", "Schedule", "Join Now"],
    bestFor: ["Boxing gyms", "Fight clubs", "Combat sports"],
    includes: [...baseIncludes, "Class schedule", "Trainer bios"],
    tags: ["boxing", "bold", "modern", "combat"],
    accent: { a: "#DC2626", b: "#1F2937", c: "#F59E0B" },
    featuredRank: 63,
    addedAt: "2026-03-19",
  },
  {
    sku: "FIT-007",
    categoryId: "fitness",
    name: "Dance Studio Playful",
    style: ["Playful", "Modern"],
    price: money(79),
    short: "Playful modern template for dance studios and classes.",
    pitch:
      "Vibrant dance studio site with class types, instructor showcase, and trial class CTA.",
    pages: ["Home", "Classes", "Instructors", "Schedule", "Join"],
    bestFor: ["Dance studios", "Dance schools", "Movement classes"],
    includes: [...baseIncludes, "Class types grid", "Instructor profiles"],
    tags: ["dance", "playful", "modern", "movement"],
    accent: { a: "#EC4899", b: "#8B5CF6", c: "#F59E0B" },
    featuredRank: 64,
    addedAt: "2026-03-19",
  },
  {
    sku: "FIT-008",
    categoryId: "fitness",
    name: "Meditation Calm",
    style: ["Minimal", "Warm"],
    price: money(69),
    short: "Minimal warm template for meditation centers and mindfulness.",
    pitch:
      "Peaceful meditation center site with class info, benefits section, and booking CTA.",
    pages: ["Home", "Sessions", "Benefits", "Teachers", "Book"],
    bestFor: ["Meditation centers", "Mindfulness studios", "Wellness"],
    includes: [...baseIncludes, "Benefits highlights", "Session types"],
    tags: ["meditation", "minimal", "warm", "mindfulness"],
    accent: { a: "#6366F1", b: "#A78BFA", c: "#DDD6FE" },
    featuredRank: 65,
    addedAt: "2026-03-19",
  },
  {
    sku: "FIT-009",
    categoryId: "fitness",
    name: "CrossFit Neon",
    style: ["Neon", "Bold"],
    price: money(99),
    short: "Neon bold template for CrossFit gyms and high-intensity training.",
    pitch:
      "Intense CrossFit gym template with WODs, community vibe, and membership signup.",
    pages: ["Home", "WODs", "Community", "Pricing", "Join"],
    bestFor: ["CrossFit gyms", "HIIT studios", "Functional fitness"],
    includes: [...baseIncludes, "WOD section", "Community highlights"],
    tags: ["crossfit", "neon", "bold", "hiit"],
    accent: { a: "#10B981", b: "#06B6D4", c: "#F59E0B" },
    featuredRank: 66,
    addedAt: "2026-03-19",
  },
  {
    sku: "FIT-010",
    categoryId: "fitness",
    name: "Personal Trainer",
    style: ["Modern", "Editorial"],
    price: money(89),
    short: "Modern editorial template for personal trainers and coaches.",
    pitch:
      "Professional trainer site with transformation stories, packages, and consultation CTA.",
    pages: ["Home", "About", "Results", "Packages", "Contact"],
    bestFor: ["Personal trainers", "Fitness coaches", "Online coaching"],
    includes: [...baseIncludes, "Transformation showcase", "Package tiers"],
    tags: ["trainer", "modern", "editorial", "coaching"],
    accent: { a: "#059669", b: "#0891B2", c: "#1E293B" },
    featuredRank: 67,
    addedAt: "2026-03-19",
  },
  {
    sku: "FIT-011",
    categoryId: "fitness",
    name: "Wellness Retreat Luxe",
    style: ["Luxury", "Elegant"],
    price: money(149),
    short: "Luxury elegant template for wellness retreats and spas.",
    pitch:
      "Premium wellness retreat with program details, accommodations, and booking system.",
    pages: ["Home", "Programs", "Accommodations", "Gallery", "Book"],
    bestFor: ["Wellness retreats", "Yoga retreats", "Spa resorts"],
    includes: [...baseIncludes, "Program cards", "Accommodation showcase"],
    tags: ["retreat", "luxury", "elegant", "wellness"],
    accent: { a: "#D97706", b: "#059669", c: "#0EA5E9" },
    featuredRank: 68,
    addedAt: "2026-03-19",
  },
  {
    sku: "BEAUTY-006",
    categoryId: "beauty",
    name: "Makeup Artist Luxe",
    style: ["Luxury", "Elegant"],
    price: money(99),
    short: "Luxury elegant template for makeup artists and beauty services.",
    pitch:
      "Premium makeup artist portfolio with services, gallery, and booking CTA.",
    pages: ["Home", "Services", "Portfolio", "Pricing", "Book"],
    bestFor: ["Makeup artists", "Bridal makeup", "Beauty services"],
    includes: [...baseIncludes, "Portfolio gallery", "Service menu"],
    tags: ["makeup", "luxury", "elegant", "beauty"],
    accent: { a: "#BE185D", b: "#EC4899", c: "#FDF2F8" },
    featuredRank: 69,
    addedAt: "2026-03-19",
  },
  {
    sku: "BEAUTY-007",
    categoryId: "beauty",
    name: "Men's Spa Bold",
    style: ["Bold", "Modern"],
    price: money(89),
    short: "Bold modern template for men's spas and grooming.",
    pitch:
      "Masculine spa template with grooming services, packages, and membership options.",
    pages: ["Home", "Services", "Packages", "Membership", "Book"],
    bestFor: ["Men's spas", "Grooming lounges", "Barber spas"],
    includes: [...baseIncludes, "Service packages", "Membership section"],
    tags: ["mens-spa", "bold", "modern", "grooming"],
    accent: { a: "#1E3A8A", b: "#3B82F6", c: "#DBEAFE" },
    featuredRank: 70,
    addedAt: "2026-03-19",
  },
  {
    sku: "BEAUTY-008",
    categoryId: "beauty",
    name: "Hair Extension Minimal",
    style: ["Minimal", "Elegant"],
    price: money(99),
    short: "Minimal elegant template for hair extensions and styling.",
    pitch:
      "Clean hair extension studio with types, care guide, and consultation booking.",
    pages: ["Home", "Extensions", "Care Guide", "Gallery", "Consult"],
    bestFor: ["Hair extensions", "Hair studios", "Premium styling"],
    includes: [...baseIncludes, "Extension types", "Care information"],
    tags: ["hair", "extensions", "minimal", "elegant"],
    accent: { a: "#92400E", b: "#D97706", c: "#FEF3C7" },
    featuredRank: 71,
    addedAt: "2026-03-19",
  },
  {
    sku: "BEAUTY-009",
    categoryId: "beauty",
    name: "Brow Bar Playful",
    style: ["Playful", "Modern"],
    price: money(69),
    short: "Playful modern template for brow bars and lash studios.",
    pitch:
      "Fun brow bar site with services, before/after gallery, and quick booking.",
    pages: ["Home", "Services", "Gallery", "Pricing", "Book Now"],
    bestFor: ["Brow bars", "Lash studios", "Beauty bars"],
    includes: [...baseIncludes, "Before/after gallery", "Quick booking"],
    tags: ["brows", "playful", "modern", "lashes"],
    accent: { a: "#DB2777", b: "#F472B6", c: "#FCE7F3" },
    featuredRank: 72,
    addedAt: "2026-03-19",
  },
  {
    sku: "BEAUTY-010",
    categoryId: "beauty",
    name: "Tattoo Studio Neon",
    style: ["Neon", "Bold"],
    price: money(89),
    short: "Neon bold template for tattoo studios and artists.",
    pitch:
      "Edgy tattoo studio with artist portfolios, flash designs, and consultation booking.",
    pages: ["Home", "Artists", "Flash", "Gallery", "Book"],
    bestFor: ["Tattoo studios", "Tattoo artists", "Body art"],
    includes: [...baseIncludes, "Artist portfolios", "Flash gallery"],
    tags: ["tattoo", "neon", "bold", "art"],
    accent: { a: "#DC2626", b: "#8B5CF6", c: "#22D3EE" },
    featuredRank: 73,
    addedAt: "2026-03-19",
  },
  {
    sku: "BEAUTY-011",
    categoryId: "beauty",
    name: "Med Spa Corp",
    style: ["Corporate", "Minimal"],
    price: money(119),
    short: "Corporate minimal template for medical spas and aesthetics.",
    pitch:
      "Professional medical spa with treatments, credentials, and consultation CTA.",
    pages: ["Home", "Treatments", "Credentials", "Results", "Consult"],
    bestFor: ["Medical spas", "Aesthetic clinics", "Dermatology"],
    includes: [...baseIncludes, "Treatment details", "Credentials display"],
    tags: ["med-spa", "corporate", "minimal", "medical"],
    accent: { a: "#0F766E", b: "#14B8A6", c: "#CCFBF1" },
    featuredRank: 74,
    addedAt: "2026-03-19",
  },
  {
    sku: "SERV-006",
    categoryId: "services",
    name: "Locksmith Pro",
    style: ["Corporate", "Bold"],
    price: money(89),
    short: "Corporate bold template for locksmith and security services.",
    pitch:
      "Trustworthy locksmith site with 24/7 emergency callout, services, and quick contact.",
    pages: ["Home", "Services", "Emergency", "Areas", "Call Now"],
    bestFor: ["Locksmiths", "Security services", "Emergency services"],
    includes: [...baseIncludes, "Emergency banner", "Service areas map"],
    tags: ["locksmith", "security", "corporate", "bold"],
    accent: { a: "#CA8A04", b: "#EAB308", c: "#FEF9C3" },
    featuredRank: 75,
    addedAt: "2026-03-19",
  },
  {
    sku: "SERV-007",
    categoryId: "services",
    name: "Landscaping Warm",
    style: ["Warm", "Modern"],
    price: money(79),
    short: "Warm modern template for landscaping and garden services.",
    pitch:
      "Friendly landscaping site with services, project gallery, and free quote CTA.",
    pages: ["Home", "Services", "Projects", "About", "Get Quote"],
    bestFor: ["Landscaping", "Garden design", "Lawn care"],
    includes: [...baseIncludes, "Project gallery", "Quote form"],
    tags: ["landscaping", "warm", "modern", "garden"],
    accent: { a: "#16A34A", b: "#84CC16", c: "#ECFCCB" },
    featuredRank: 76,
    addedAt: "2026-03-19",
  },
  {
    sku: "SERV-008",
    categoryId: "services",
    name: "Electrician Bold",
    style: ["Bold", "Corporate"],
    price: money(89),
    short: "Bold corporate template for electricians and electrical services.",
    pitch:
      "Professional electrician site with services, emergency callout, and instant quote.",
    pages: ["Home", "Services", "Emergency", "Reviews", "Contact"],
    bestFor: ["Electricians", "Electrical contractors", "Emergency repairs"],
    includes: [...baseIncludes, "Emergency section", "Review highlights"],
    tags: ["electrician", "bold", "corporate", "emergency"],
    accent: { a: "#2563EB", b: "#FBBF24", c: "#DBEAFE" },
    featuredRank: 77,
    addedAt: "2026-03-19",
  },
  {
    sku: "SERV-009",
    categoryId: "services",
    name: "Plumbing Emergency",
    style: ["Modern", "Bold"],
    price: money(89),
    short: "Modern bold template for plumbers and emergency plumbing.",
    pitch:
      "Fast-action plumber site with 24/7 emergency banner, services, and quick call CTA.",
    pages: ["Home", "Services", "Emergency", "Pricing", "Call Now"],
    bestFor: ["Plumbers", "Emergency plumbing", "Drain services"],
    includes: [...baseIncludes, "24/7 emergency banner", "Pricing guide"],
    tags: ["plumbing", "modern", "bold", "emergency"],
    accent: { a: "#0284C7", b: "#0EA5E9", c: "#E0F2FE" },
    featuredRank: 78,
    addedAt: "2026-03-19",
  },
  {
    sku: "SERV-010",
    categoryId: "services",
    name: "Moving Company",
    style: ["Corporate", "Modern"],
    price: money(99),
    short: "Corporate modern template for moving companies and movers.",
    pitch:
      "Professional moving company with services, free quote calculator, and booking system.",
    pages: ["Home", "Services", "Quote", "Reviews", "Book"],
    bestFor: ["Moving companies", "Relocation services", "Storage"],
    includes: [...baseIncludes, "Quote calculator", "Booking flow"],
    tags: ["moving", "corporate", "modern", "relocation"],
    accent: { a: "#DC2626", b: "#F59E0B", c: "#FEF3C7" },
    featuredRank: 79,
    addedAt: "2026-03-19",
  },
  {
    sku: "SERV-011",
    categoryId: "services",
    name: "Pet Grooming Playful",
    style: ["Playful", "Warm"],
    price: money(79),
    short: "Playful warm template for pet grooming and pet care.",
    pitch:
      "Friendly pet grooming site with services, packages, and online booking.",
    pages: ["Home", "Services", "Packages", "Gallery", "Book"],
    bestFor: ["Pet grooming", "Dog salons", "Pet spas"],
    includes: [...baseIncludes, "Service packages", "Pet gallery"],
    tags: ["pet-grooming", "playful", "warm", "pets"],
    accent: { a: "#F97316", b: "#FB923C", c: "#FFEDD5" },
    featuredRank: 80,
    addedAt: "2026-03-19",
  }
];
